version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(levelname)8s - %(message)s"
    detailed:
        format: "%(asctime)s - %(levelname)8s - %(name)15s  - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: /AppTestFramework/logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    suite_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: /AppTestFramework/logs/suite_execution.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    __main__:
        level: DEBUG
        handlers: [console, debug_file_handler]
        propagate: no

    suite:
        level: DEBUG
        handlers: [console, debug_file_handler, suite_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [console, debug_file_handler, suite_file_handler]